export const GET_AI_DETAILS = "GET_AI_DETAILS";
export const UPDATE_AI_DETAILS = "UPDATE_AI_DETAILS";
export const EDIT_AI_DETAILS = "EDIT_AI_DETAILS";
export const LOGGING_ERR = "LOGGING_ERR";
export const UPLOAD_PHOTOGRAPH = "UPLOAD_PHOTOGRAPH";
export const GET_BLOB = "GET_BLOB";
export const DELETE_PHOTOGRAPH = "DELETE_PHOTOGRAPH";
export const EDIT_PHOTOGRAPH = "EDIT_PHOTOGRAPH";
