export const action_contants = {
  GET_AI_DETAILS: "GET_AI_DETAILS",
  UPDATE_AI_DETAILS: "UPDATE_AI_DETAILS",
  EDIT_AI_DETAILS: "EDIT_AI_DETAILS",
  LOGGING_ERR: "LOGGING_ERR",
  UPLOAD_PHOTOGRAPH: "UPLOAD_PHOTOGRAPH",
  GET_BLOB: "GET_BLOB",
  DELETE_PHOTOGRAPH: "DELETE_PHOTOGRAPH",
  EDIT_PHOTOGRAPH: "EDIT_PHOTOGRAPH",
  GET_AUDIT_DETAILS: "GET_AUDIT_DETAILS",
  USER_LOGIN: "USER_LOGIN",
  SUCCESS: "SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  CLEAR: "CLEAR",
  GETVSLCODE: "GETVSLCODE"
};
